apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/thelogicguy/python-kubernetes"
    path: python-app-project
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  