image:
  repository: thelogicguy/complete-devops-project
  tag: a83fc38
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false