image:
  repository: thelogicguy/complete-devops-project
  tag: 61c062b
  pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false