---
name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set short sha
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV  # This command extracts the first 7 characters of the commit SHA and sets it as an environment variable named SHORT_SHA.
    
      - name: Build Docker image
        run: |
          docker build -t thelogicguy/complete_devops_project:${{ env.SHORT_SHA }} .
    