---
name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t thelogicguy/complete-devops-project:${{ env.SHORT_SHA }} .

      - name: Push to Docker
        run: |
          docker push thelogicguy/complete-devops-project:${{ env.SHORT_SHA }}
          docker tag thelogicguy/complete-devops-project:${{ env.SHORT_SHA }} thelogicguy/complete-devops-project:latest
          docker push thelogicguy/complete-devops-project:latest