---
name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t thelogicguy/complete-devops-project:${{ env.SHORT_SHA }} .

      - name: Push to Docker
        run: |
          docker push thelogicguy/complete-devops-project:${{ env.SHORT_SHA }}
      
      - name: Configure Git Aurthor
        run: |
          git config --global user.name "thelogicguy"
          git config --global user.email "07140254+thelogicguy@users.noreply.github.com"

      - name: Update Helm Chat with new image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.SHORT_SHA }}/" python-app-project/values.yml
          git add ./python-app-project/values.yml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push

      